### PR TITLE
Enhance Connection (Support -SkipCertificateCheck)

### PR DESCRIPTION
**Pull request by alagoutte**
and also fix indent...

### CODE REVIEW

**Comment by alagoutte** [comment]
it will be fix #8

**Comment by benclaussen1** [comment]
This all looks good! Thanks! My only concern is some formatting. I do my best to follow the guidelines from [Powershell Practice and Style](https://poshcode.gitbook.io/powershell-practice-and-style/) (yes... there are certainly places where it is not followed, and I would like to correct all that... I started this module long ago 😅). In this instance, I am referencing the [One True Brace Style](https://poshcode.gitbook.io/powershell-practice-and-style/style-guide/code-layout-and-formatting#one-true-brace-style):

```Powershell
# Instead of 
try {
    Do-Thing
}
catch {
    throw 'Error'
}

# The OTBS prefers
try {
    Do-Thing
} catch {
    throw 'Error'
}
```

> The primary reason for this recommendation is practical: there are no exceptions necessary when following this rule, and when code is written following this style, **new lines of code can be inserted between any two lines with no risk of accidentally breaking the code** by separating braces from their statement blocks. Thus, it's easier to follow, and makes errors less likely.

Unless you want to correct the braces now, I can correct them later with another commit. Not a big deal at the moment and I can merge this to master to get a new release out.

**Comment by alagoutte** [comment]
Hi Ben,

i will look how to configure Visual Code Formatter to use this formatting :)

**Comment by alagoutte** [comment]
Thanks for the merge !

**Pull request merged**
