### PR TITLE
Device port support

### PR DESCRIPTION
**Pull request by SheffSix**
Added functions to work with Rear and Front ports.

Added a function to get tag information so ports can be tagged by the tag's slug without knowing the ID. Plan to add tag paramaters to existing functions soon.

```powershell
Add-NetboxDCIMRearPort -Device 123 -Name Test -Type 110-punch -Tags "$((Get-NetboxTag -Slug tag-no-1).id)","$((Get-NetboxTag -slug another-tag).id)"
```

I've taken previous concerns about using validateset onboard, so have only used validation to ensure color is submitted as RGB Hex.

Started Cable and Cable Termination functions. They are only GET functions for now. Hopefully I will be expanding as this is a big part of what I am looking to use the module for at my workplace.

Fingers crossed I haven't stood on any toes here - I realise this is a fairly major, unannounced pull request, and somewhat incomplete, so apologies 😅

### CODE REVIEW

**Comment by benclaussen** [comment]
Thank you! This looks great @SheffSix. Even adding to the Postman collection, I appreciate that! 

My only ask is that you reformat using [OTBS ](https://poshcode.gitbook.io/powershell-practice-and-style/style-guide/code-layout-and-formatting#one-true-brace-style) to follow the rest of the module. I do my best to adhere to [Powershell Practice and Style ](https://poshcode.gitbook.io/powershell-practice-and-style/introduction/readme) guide

**Comment by SheffSix** [comment]
I wasn't sure about the postman, so I stopped but I'll go back through.
What does it do just out of curiosity? Showing my ignorance 😒

 I followed formatting of existing functions as best I could but again I
will go back through with guidelines in mind

More pull requests to come once I've got my head around how to work with
terminations

James

**Comment by benclaussen** [comment]
No worries! Everyone has to start somewhere. [Postman ](https://www.postman.com/) is a powerful utility for testing APIs. If you were manually editing that json file then I will need to test import to ensure it imports the collection properly. From a quick brief review though it looks correct.

**Comment by SheffSix** [comment]
I think I'm done committing stuff to this PR now

**Pull request merged**
